# Generated by Django 5.2.17 on 2026-09-01 07:33

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, validators=[core.validators.validate_card_number], verbose_name='شماره کارت')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='نام بانک')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='شماره حساب (اختیاری)')),
                ('is_cash', models.BooleanField(default=False, verbose_name='نقدی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_cards', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کارت',
                'verbose_name_plural': 'کارت\u200cها',
                'ordering': ['-is_cash', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('transfer_date', models.DateField(verbose_name='تاریخ انتقال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='banking.bankcard', verbose_name='از کارت')),
            ],
            options={
                'verbose_name': 'انتقال',
                'verbose_name_plural': 'انتقال\u200cها',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
    ]
