# Generated by Django 5.2.17 on 2026-09-01 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='incoming_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfer', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='outgoing_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfer', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='banking.bankcard', verbose_name='به کارت'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
