# Generated by Django 5.2.17 on 2026-09-01 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bankcard',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cash', True)), fields=('user',), name='unique_cash_card_per_user'),
        ),
    ]
