# Generated by Django 5.1.15 on 2026-09-02 02:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_bankcard_unique_cash_card_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bankcard',
            constraint=models.UniqueConstraint(condition=models.Q(('card_number__isnull', False), models.Q(('card_number', ''), _negated=True)), fields=('user', 'card_number'), name='unique_card_number_per_user'),
        ),
    ]
